"""Generate Mermaid diagrams for the saddlery core.

Pure render functions are unit-tested; `main()` shells to pyreverse and writes
markdown files, and is covered by the CI smoke run.
"""

from __future__ import annotations

import importlib
import inspect
import pkgutil
import re
import subprocess
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

from saddlery.events import (
    AssistantMessage,
    AssistantMessageDelta,
    BaseEvent,
    ErrorEvent,
    RunFinished,
    RunStarted,
    ToolCall,
    ToolResult,
    UserMessage,
)
from saddlery.messages import Message

if TYPE_CHECKING:
    from collections.abc import Sequence

    from pydantic import BaseModel


_HERE = Path(__file__).resolve()
BACKEND_DIR = _HERE.parents[1]
REPO_ROOT = _HERE.parents[2]
DIAGRAMS_DIR = REPO_ROOT / "docs" / "diagrams"

_GENERATED_BANNER = (
    "<!-- Generated by backend/scripts/gen_diagrams.py — do not edit. "
    "Regenerate with `make diagrams`. -->"
)

GROUP_ORDER: list[str] = ["agent", "llm", "session", "transport", "events", "messages"]

ER_MODELS: list[type[BaseModel]] = [
    BaseEvent,
    UserMessage,
    RunStarted,
    AssistantMessageDelta,
    AssistantMessage,
    ToolCall,
    ToolResult,
    RunFinished,
    ErrorEvent,
    Message,
]


def _type_token(annotation: str) -> str:
    """Collapse a (string) annotation into a Mermaid-safe attribute type token."""
    token = re.sub(r"\W+", "_", annotation).strip("_")
    return token or "object"


def _own_annotations(model: type[BaseModel]) -> dict[str, str]:
    """Only the fields declared on `model` itself (not inherited).

    Modules use `from __future__ import annotations`, so values are strings.
    """
    return dict(model.__dict__.get("__annotations__", {}))


def render_er(models: Sequence[type[BaseModel]]) -> str:
    """Render the given models as a Mermaid `erDiagram`.

    Each model becomes an entity listing its own fields; a model whose base is
    also in `models` gets an `is a` relationship to that base.
    """
    listed = set(models)
    lines = ["erDiagram"]
    for model in models:
        lines.append(f"  {model.__name__} {{")
        for name, annotation in _own_annotations(model).items():
            lines.append(f"    {_type_token(annotation)} {name}")
        lines.append("  }")
    for model in models:
        parent = next((b for b in model.__mro__[1:] if b in listed), None)
        if parent is not None:
            lines.append(f'  {parent.__name__} ||--|| {model.__name__} : "is a"')
    return "\n".join(lines) + "\n"


def _wrap_md(title: str, mermaid: str) -> str:
    return f"{_GENERATED_BANNER}\n\n# {title}\n\n```mermaid\n{mermaid.strip()}\n```\n"


def render_class_md(mmd: str) -> str:
    """Wrap raw pyreverse Mermaid in a titled, fenced, banner-marked markdown page."""
    return _wrap_md("Core class diagram", mmd)


def render_package_md(mmd: str) -> str:
    """Wrap raw pyreverse package Mermaid in a titled, banner-marked markdown page."""
    return _wrap_md("Core package diagram", mmd)


def _pyreverse_mmd() -> tuple[str, str]:
    """Run pyreverse once over `saddlery`, returning its class and package Mermaid.

    A single run emits both `classes_saddlery.mmd` and `packages_saddlery.mmd`.
    """
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            ["pyreverse", "-o", "mmd", "-p", "saddlery", "-d", tmp, "saddlery"],
            cwd=BACKEND_DIR,
            check=True,
        )
        classes = (Path(tmp) / "classes_saddlery.mmd").read_text()
        packages = (Path(tmp) / "packages_saddlery.mmd").read_text()
        return classes, packages


def _group_key(module: str) -> str:
    """The sub-package under `saddlery` (e.g. 'saddlery.llm.base' -> 'llm')."""
    prefix = "saddlery."
    if not module.startswith(prefix):
        return ""
    return module[len(prefix) :].split(".")[0]


def reorder_class_diagram(mmd: str, class_module: dict[str, str]) -> str:
    """Reshape pyreverse Mermaid: relationships first, then classes grouped by module.

    Class blocks are ordered by `GROUP_ORDER` (unknown modules last), then by name.
    Relationship lines keep pyreverse's order and move above the class blocks.
    """
    lines = mmd.splitlines()
    blocks: list[tuple[str, list[str]]] = []
    rels: list[str] = []
    i = 0
    while i < len(lines) and lines[i].strip() != "classDiagram":
        i += 1
    i += 1  # skip the header
    while i < len(lines):
        line = lines[i]
        match = re.match(r"\s*class\s+(\w+)", line)
        if match:
            block = [line]
            i += 1
            if "{" in line and "}" not in line:
                while i < len(lines) and "}" not in lines[i]:
                    block.append(lines[i])
                    i += 1
                if i < len(lines):
                    block.append(lines[i])
                    i += 1
            blocks.append((match.group(1), block))
        elif line.strip():
            rels.append(line)
            i += 1
        else:
            i += 1

    def rank(name: str) -> int:
        key = _group_key(class_module.get(name, ""))
        return GROUP_ORDER.index(key) if key in GROUP_ORDER else len(GROUP_ORDER)

    blocks.sort(key=lambda nb: (rank(nb[0]), nb[0]))
    out = ["classDiagram", *rels]
    for _, block in blocks:
        out.extend(block)
    return "\n".join(out) + "\n"


def _saddlery_class_modules() -> dict[str, str]:
    """Map each saddlery class name to the module that defines it."""
    import saddlery

    mapping: dict[str, str] = {}
    for info in pkgutil.walk_packages(saddlery.__path__, prefix="saddlery."):
        module = importlib.import_module(info.name)
        for name, obj in inspect.getmembers(module, inspect.isclass):
            if obj.__module__ == info.name:
                mapping[name] = obj.__module__
    return mapping


def main() -> None:
    DIAGRAMS_DIR.mkdir(parents=True, exist_ok=True)
    classes, packages = _pyreverse_mmd()
    ordered = reorder_class_diagram(classes, _saddlery_class_modules())
    (DIAGRAMS_DIR / "class-core.md").write_text(render_class_md(ordered))
    (DIAGRAMS_DIR / "packages-core.md").write_text(render_package_md(packages))
    (DIAGRAMS_DIR / "events-er.md").write_text(
        _wrap_md("Core data model (events + messages)", render_er(ER_MODELS))
    )


if __name__ == "__main__":
    main()
