"""Generate Mermaid diagrams for the saddlery core.

Pure render functions are unit-tested; `main()` shells to pyreverse and writes
markdown files, and is covered by the CI smoke run.
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

from saddlery.events import (
    AssistantMessage,
    AssistantMessageDelta,
    BaseEvent,
    ErrorEvent,
    RunFinished,
    RunStarted,
    UserMessage,
)
from saddlery.messages import Message

if TYPE_CHECKING:
    from collections.abc import Sequence

    from pydantic import BaseModel


_HERE = Path(__file__).resolve()
CORE_DIR = _HERE.parents[1]
REPO_ROOT = _HERE.parents[2]
DIAGRAMS_DIR = REPO_ROOT / "docs" / "diagrams"

_GENERATED_BANNER = (
    "<!-- Generated by core/scripts/gen_diagrams.py — do not edit. "
    "Regenerate with `make diagrams`. -->"
)

ER_MODELS: list[type[BaseModel]] = [
    BaseEvent,
    UserMessage,
    RunStarted,
    AssistantMessageDelta,
    AssistantMessage,
    RunFinished,
    ErrorEvent,
    Message,
]


def _type_token(annotation: str) -> str:
    """Collapse a (string) annotation into a Mermaid-safe attribute type token."""
    token = re.sub(r"\W+", "_", annotation).strip("_")
    return token or "object"


def _own_annotations(model: type[BaseModel]) -> dict[str, str]:
    """Only the fields declared on `model` itself (not inherited).

    Modules use `from __future__ import annotations`, so values are strings.
    """
    return dict(model.__dict__.get("__annotations__", {}))


def render_er(models: Sequence[type[BaseModel]]) -> str:
    """Render the given models as a Mermaid `erDiagram`.

    Each model becomes an entity listing its own fields; a model whose base is
    also in `models` gets an `is a` relationship to that base.
    """
    listed = set(models)
    lines = ["erDiagram"]
    for model in models:
        lines.append(f"  {model.__name__} {{")
        for name, annotation in _own_annotations(model).items():
            lines.append(f"    {_type_token(annotation)} {name}")
        lines.append("  }")
    for model in models:
        parent = next((b for b in model.__mro__[1:] if b in listed), None)
        if parent is not None:
            lines.append(f'  {parent.__name__} ||--|| {model.__name__} : "is a"')
    return "\n".join(lines) + "\n"


def _wrap_md(title: str, mermaid: str) -> str:
    return f"{_GENERATED_BANNER}\n\n# {title}\n\n```mermaid\n{mermaid.strip()}\n```\n"


def render_class_md(mmd: str) -> str:
    """Wrap raw pyreverse Mermaid in a titled, fenced, banner-marked markdown page."""
    return _wrap_md("Core class diagram", mmd)


def _pyreverse_class_mmd() -> str:
    """Run pyreverse over the saddlery package and return its Mermaid class diagram."""
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            ["pyreverse", "-o", "mmd", "-p", "saddlery", "-d", tmp, "saddlery"],
            cwd=CORE_DIR,
            check=True,
        )
        return (Path(tmp) / "classes_saddlery.mmd").read_text()


def main() -> None:
    DIAGRAMS_DIR.mkdir(parents=True, exist_ok=True)
    (DIAGRAMS_DIR / "class-core.md").write_text(render_class_md(_pyreverse_class_mmd()))
    (DIAGRAMS_DIR / "events-er.md").write_text(
        _wrap_md("Core data model (events + messages)", render_er(ER_MODELS))
    )


if __name__ == "__main__":
    main()
